# SPDX-FileCopyrightText: 2026 University of Manchester
#
# SPDX-License-Identifier: apache-2.0

[build-system]
requires = ["setuptools>=82"]
build-backend = "setuptools.build_meta"

[project]
name = "wrf_analysis_toolkit"
version = "2.4.3"
requires-python = ">=3.10"
dependencies = [
    "netCDF4>=1.7",
    "matplotlib>=3.11",
    "cmasher>=1.9",
    "cartopy>=0.25",
    "imageio>=2.37",
    "imageio-ffmpeg>=0.6",
    "metpy>=1.7",
]

[project.scripts]
wrf_analysis_toolkit_cli = "wrf_analysis_toolkit.cli:cli"

[tool.setuptools.package-data]
wrf_analysis_toolkit = [
    "cartopy_data/**/*"
]
