# SPDX-FileCopyrightText: 2026 University of Manchester
#
# SPDX-License-Identifier: apache-2.0

[build-system]
requires = ["setuptools>=82"]
build-backend = "setuptools.build_meta"

[project]
name = "rip_toolkit"
version = "1.4.1"
requires-python = ">=3.10"
dependencies = [
    "netCDF4>=1.7",
]


[project.scripts]
rip_toolkit_cli = "rip_toolkit.cli:cli"

[tool.setuptools.package-data]
rip_toolkit = [
    "sample_data/**/*"
]
