# SPDX-FileCopyrightText: 2024 University of Manchester
#
# SPDX-License-Identifier: apache-2.0

name: Add License and Copyright Headers
on: pull_request

jobs:
  check:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    permissions:
      pull-requests: write
      contents: write
    uses: UoMResearchIT/actions/.github/workflows/apply-reuse.yml@bd6d27b15d37f7bf55813ffb393b118aa6f1d72a
